# Generated by Django 5.0.7 on 2024-07-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='addedDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
